### ISSUE TITLE
Issue in missingnumbers.cpp

### ISSUE THREAD

**Issue by offencive** [haotian-wu/Hackerrank_solutions#2]
Hola!
There was a print error in your code. Kindly change it to the following:

```    //printing o/p
    for(map<int,int> :: iterator j = mp.begin(); j!=mp.end(); j++){
        if(j->second>0){
            cout<<j->first<<" ";
        }
    }
```
Thanks

**Comment by haotian-wu** [comment]
Thanks! I tested a few times and it seems my approach works as well, but I think yours is better because of some buffer flush issue.
